# 
service: gym-reservation
provider:
  name: aws
  runtime: python3.8
  stage: dev
plugins:
  - serverless-python-requirements
functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
